name: Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Synapse access token copy
        run: |
          sed -i 's/synapsePersonalAccessToken = ""/synapsePersonalAccessToken = "${{ secrets.SYNAPSE_PAT }}"/' ${GITHUB_WORKSPACE}/DataMigration/src/main/java/org/sagebionetoworks/dian/datamigration/SynapseUtil.java
          
      - name: Bridge auth copy 1
        run: |
          sed -i 's/bridgeAdminEmail = ""/bridgeAdminEmail = "${{ secrets.BRIDGE_EMAIL }}"/' ${GITHUB_WORKSPACE}/DataMigration/src/main/java/org/sagebionetoworks/dian/datamigration/BridgeUtil.java
          
      - name: Bridge auth copy 2
        run: |
          sed -i 's/bridgeAdminPassword = ""/bridgeAdminPassword = "${{ secrets.BRIDGE_EMAIL }}"/' ${GITHUB_WORKSPACE}/DataMigration/src/main/java/org/sagebionetoworks/dian/datamigration/BridgeUtil.java
                  
      - name: Unit Test
        run: ./gradlew test

      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # IMPORTANT: Upload reports regardless of status
        with:
          name: UnitTestResults
          path: DataMigration/build/test-results/test/*.xml # path to where the xml test results are stored
          
      - name: Build executable jar
        run: ./gradlew jar
          
      - name: Run DataMigration
        run: java -jar ${GITHUB_WORKSPACE}/DataMigration/build/libs/DataMigration.jar
          
